['/usr/X11R6/lib/X11/fonts/TTF', '/usr/X11R6/lib/X11/fonts/Type1', '/usr/share/fonts/bitmap-fonts', '/usr/share/fonts/openoffice', '/usr/share/fonts/monotype', '/usr/share/fonts/default', '/usr/share/fonts/bitstream-vera', '/usr/share/fonts/default/Type1', '/usr/share/fonts/default/ghostscript', '/usr/X11R6/lib/X11/fonts/TTF', '/usr/X11R6/lib/X11/fonts/75dpi', '/usr/X11R6/lib/X11/fonts/Type1', '/usr/X11R6/lib/X11/fonts/util', '/usr/X11R6/lib/X11/fonts/misc', '/usr/X11R6/lib/X11/fonts/100dpi', '/usr/X11R6/lib/X11/fonts/encodings', '/usr/X11R6/lib/X11/fonts/local', '/usr/X11R6/lib/X11/fonts/CID', '/usr/X11R6/lib/X11/fonts/OTF', '/usr/X11R6/lib/X11/fonts/encodings/large']
from kaplot.text.fonts import fontFamilies, FontFamily, \
     serif, sans_serif, monospace, cursive, fantasy, symbols, other, generics

import kaplot
kaplot.searchforfonts = False

fontFamilies['URW Palladio L'] = FontFamily(name='URW Palladio L', genericFontFamily=serif, regular='/usr/share/fonts/default/Type1/p052003l.pfb', bold='/usr/share/fonts/default/Type1/p052004l.pfb', italic='/usr/share/fonts/default/Type1/p052023l.pfb', bolditalic='/usr/share/fonts/default/Type1/p052024l.pfb')
fontFamilies['Nimbus Mono L'] = FontFamily(name='Nimbus Mono L', genericFontFamily=monospace, regular='/usr/share/fonts/default/Type1/n022003l.pfb', bold='/usr/share/fonts/default/Type1/n022004l.pfb', italic='/usr/share/fonts/default/Type1/n022023l.pfb', bolditalic='/usr/share/fonts/default/Type1/n022024l.pfb')
fontFamilies['Century Schoolbook L'] = FontFamily(name='Century Schoolbook L', genericFontFamily=serif, regular='/usr/share/fonts/default/Type1/c059013l.pfb', bold='/usr/share/fonts/default/Type1/c059016l.pfb', italic='/usr/share/fonts/default/Type1/c059033l.pfb', bolditalic='/usr/share/fonts/default/Type1/c059036l.pfb')
fontFamilies['Dingbats'] = FontFamily(name='Dingbats', genericFontFamily=symbols, regular='/usr/share/fonts/default/Type1/d050000l.pfb', bold='/usr/share/fonts/default/Type1/d050000l.pfb', italic='/usr/share/fonts/default/Type1/d050000l.pfb', bolditalic='/usr/share/fonts/default/Type1/d050000l.pfb')
fontFamilies['Cumberland AMT'] = FontFamily(name='Cumberland AMT', genericFontFamily=sans_serif, regular='/usr/share/fonts/monotype/Cumbwr__.ttf', bold='/usr/share/fonts/monotype/cumbwb__.ttf', italic='/usr/share/fonts/monotype/cumbwi__.ttf', bolditalic='/usr/share/fonts/monotype/cumbwbi_.ttf')
fontFamilies['Standard Symbols L'] = FontFamily(name='Standard Symbols L', genericFontFamily=symbols, regular='/usr/share/fonts/default/Type1/s050000l.pfb', bold='/usr/share/fonts/default/Type1/s050000l.pfb', italic='/usr/share/fonts/default/Type1/s050000l.pfb', bolditalic='/usr/share/fonts/default/Type1/s050000l.pfb')
fontFamilies['Bitstream Vera Sans'] = FontFamily(name='Bitstream Vera Sans', genericFontFamily=sans_serif, regular='/usr/share/fonts/bitstream-vera/Vera.ttf', bold='/usr/share/fonts/bitstream-vera/VeraBd.ttf', italic='/usr/share/fonts/bitstream-vera/VeraIt.ttf', bolditalic='/usr/share/fonts/bitstream-vera/VeraBI.ttf')
fontFamilies['Bitstream Vera Sans Mono'] = FontFamily(name='Bitstream Vera Sans Mono', genericFontFamily=sans_serif, regular='/usr/share/fonts/bitstream-vera/VeraMono.ttf', bold='/usr/share/fonts/bitstream-vera/VeraMoBd.ttf', italic='/usr/share/fonts/bitstream-vera/VeraMoIt.ttf', bolditalic='/usr/share/fonts/bitstream-vera/VeraMoBI.ttf')
fontFamilies['OpenSymbol'] = FontFamily(name='OpenSymbol', genericFontFamily=sans_serif, regular='/usr/share/fonts/openoffice/opens___.ttf', bold='/usr/share/fonts/openoffice/opens___.ttf', italic='/usr/share/fonts/openoffice/opens___.ttf', bolditalic='/usr/share/fonts/openoffice/opens___.ttf')
fontFamilies['Thorndale AMT'] = FontFamily(name='Thorndale AMT', genericFontFamily=sans_serif, regular='/usr/share/fonts/monotype/THOWR___.ttf', bold='/usr/share/fonts/monotype/THOWB___.ttf', italic='/usr/share/fonts/monotype/THOWI___.ttf', bolditalic='/usr/share/fonts/monotype/THOWBI__.ttf')
fontFamilies['Nimbus Roman No9 L'] = FontFamily(name='Nimbus Roman No9 L', genericFontFamily=serif, regular='/usr/share/fonts/default/Type1/n021003l.pfb', bold='/usr/share/fonts/default/Type1/n021004l.pfb', italic='/usr/share/fonts/default/Type1/n021023l.pfb', bolditalic='/usr/share/fonts/default/Type1/n021024l.pfb')
fontFamilies['URW Gothic L'] = FontFamily(name='URW Gothic L', genericFontFamily=sans_serif, regular='/usr/share/fonts/default/Type1/a010013l.pfb', bold='/usr/share/fonts/default/Type1/a010013l.pfb', italic='/usr/share/fonts/default/Type1/a010033l.pfb', bolditalic='/usr/share/fonts/default/Type1/a010013l.pfb')
fontFamilies['Bitstream Vera Serif'] = FontFamily(name='Bitstream Vera Serif', genericFontFamily=sans_serif, regular='/usr/share/fonts/bitstream-vera/VeraSe.ttf', bold='/usr/share/fonts/bitstream-vera/VeraSeBd.ttf', italic='/usr/share/fonts/bitstream-vera/VeraSe.ttf', bolditalic='/usr/share/fonts/bitstream-vera/VeraSe.ttf')
fontFamilies['Nimbus Sans L Condensed'] = FontFamily(name='Nimbus Sans L Condensed', genericFontFamily=sans_serif, regular='/usr/share/fonts/default/Type1/n019043l.pfb', bold='/usr/share/fonts/default/Type1/n019044l.pfb', italic='/usr/share/fonts/default/Type1/n019063l.pfb', bolditalic='/usr/share/fonts/default/Type1/n019064l.pfb')
fontFamilies['URW Chancery L'] = FontFamily(name='URW Chancery L', genericFontFamily=cursive, regular='/usr/share/fonts/default/Type1/z003034l.pfb', bold='/usr/share/fonts/default/Type1/z003034l.pfb', italic='/usr/share/fonts/default/Type1/z003034l.pfb', bolditalic='/usr/share/fonts/default/Type1/z003034l.pfb')
fontFamilies['Courier 10 Pitch'] = FontFamily(name='Courier 10 Pitch', genericFontFamily=sans_serif, regular='/usr/X11R6/lib/X11/fonts/Type1/c0419bt_.pfb', bold='/usr/X11R6/lib/X11/fonts/Type1/c0583bt_.pfb', italic='/usr/X11R6/lib/X11/fonts/Type1/c0582bt_.pfb', bolditalic='/usr/X11R6/lib/X11/fonts/Type1/c0611bt_.pfb')
fontFamilies['Albany AMT'] = FontFamily(name='Albany AMT', genericFontFamily=sans_serif, regular='/usr/share/fonts/monotype/albw.ttf', bold='/usr/share/fonts/monotype/albwb.ttf', italic='/usr/share/fonts/monotype/albwi.ttf', bolditalic='/usr/share/fonts/monotype/albwbi.ttf')
fontFamilies['URW Bookman L'] = FontFamily(name='URW Bookman L', genericFontFamily=serif, regular='/usr/share/fonts/default/Type1/b018012l.pfb', bold='/usr/share/fonts/default/Type1/b018015l.pfb', italic='/usr/share/fonts/default/Type1/b018032l.pfb', bolditalic='/usr/share/fonts/default/Type1/b018035l.pfb')
fontFamilies['Bitstream Charter'] = FontFamily(name='Bitstream Charter', genericFontFamily=sans_serif, regular='/usr/X11R6/lib/X11/fonts/Type1/c0648bt_.pfb', bold='/usr/X11R6/lib/X11/fonts/Type1/c0632bt_.pfb', italic='/usr/X11R6/lib/X11/fonts/Type1/c0649bt_.pfb', bolditalic='/usr/X11R6/lib/X11/fonts/Type1/c0633bt_.pfb')
fontFamilies['Nimbus Sans L'] = FontFamily(name='Nimbus Sans L', genericFontFamily=sans_serif, regular='/usr/share/fonts/default/Type1/n019003l.pfb', bold='/usr/share/fonts/default/Type1/n019004l.pfb', italic='/usr/share/fonts/default/Type1/n019023l.pfb', bolditalic='/usr/share/fonts/default/Type1/n019024l.pfb')
for generic in generics:
	generic.sort()
